# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.1
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=0.0.1-1.21.1
maven_group=net.myriantics.template
mod_id=template
mod_name=Myriantics' Template Mod
mod_description=This is an example description! Tell everyone what your mod is about!

# Dependencies
fabric_api_version=0.145.4+26.1.1