# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.5
loom_version=1.18-SNAPSHOT

# Mod Properties
mod_version=1.0.0-26.2-fabric
maven_group=net.myriantics.weve_got_beef
mod_id=weve-got-beef
mod_name=We've Got Beef
mod_description=Has the passage of time eaten away at your petty grudges? Perpetuate them as long as you like with this mod.

# Dependencies
fabric_api_version=0.161.0+26.2
modmenu_version=20.0.3
yacl_version=3.9.7+26.2-fabric